---
type: golang
license: Apache Version 2
labels:
  author: gatblau
  application: boot
  description: merges environment variables into configuration files
  architecture: amd64
env:
  CGO_ENABLED: 0
  GOARCH: amd64
profiles:
  - name: linux
    labels:
      platform: linux
    env:
      GOOS: linux
    run:
      - go fmt
      - go build -o boot-linux-amd64 -v
    target: boot-linux-amd64
  - name: darwin
    labels:
      platform: darwin
    env:
      GOOS: linux
    run:
      - go fmt
      - go build -o boot-darwin-amd64 -v
    target: boot-darwin-amd64
...